language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
install:
  - cargo benchcmp --version || cargo install cargo-benchcmp
cache: cargo
script:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo test --features nightly; else cargo test; fi
after_script:
  - ./travis-after-script.sh
